### ISSUE TITLE
Do we need to be consistent in the testing tools we use?

### ISSUE THREAD

**Issue by McEileen** [Tweechable/tweechable_final#113]
(I wasn't sure if I should write this in our Slack channel or here.....)

I'm going to start writing tests for the tweet order problem (see issue #69) and I plan on writing them in rspec, as that's the only Ruby on Rails testing tool I've ever used.  The tests we already have (I think @TheJhyde wrote a majority of them) don't use RSpec.  Is it okay if I write tests in RSpec, even though we haven't been using that tool so far?

**Comment by vkoves** [comment]
What's the current tool being used? I'd say that most Rails test systems
are so similar (and relatively easy to learn), that we should stick to one
tool, unless tools test different parts of the app (e.g. Mocha for JS).
However, if you feel significantly more comfortable in RSpec, I don't think
it's a big deal as long as Travis can run both together properly.

On May 8, 2017 11:12 PM, "McEileen" <notifications@github.com> wrote:

(I wasn't sure if I should write this in our Slack channel or here.....)

I'm going to start writing tests for the tweet order problem (see issue #69
<https://github.com/Tweechable/tweechable_final/issues/69>) and I plan on
writing them in rspec, as that's the only Ruby on Rails testing tool I've
ever used. The tests we already have (I think @TheJhyde
<https://github.com/TheJhyde> wrote a majority of them) don't use RSpec. Is
it okay if I write tests in RSpec, even though we haven't been using that
tool so far?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Tweechable/tweechable_final/issues/113>, or mute the
thread

**Comment by McEileen** [comment]
The tests use minitest and the test file structure that Rails default creates when you generate the models, controllers, etc.  I think you're right that it's good to be consistent, especially because I think it will be relatively simple to pick up minitest.  Thanks for the feedback!  I'm going to write all my tests in minitest.  Time for fun with fixtures. 🙌
