### ISSUE TITLE
Start to capture offending tweets to form a database for sentiment analysis

### ISSUE THREAD

**Issue by kevinpuj** [Tweechable/tweechable_final#27]

**Comment by McEileen** [comment]
While I think this is a good idea, I'm closing the issue in order to keep our issue tracker fresh because this issue has been open for over nine months without any activity on it.  Also, the long-term idea store currently has a similar goal ["Semantic analysis of tweets before and after lesson"](https://github.com/Tweechable/tweechable_final/projects/2) in the long-term area.
