### ISSUE TITLE
Create method to stop receiving tweets from tweechable

### ISSUE THREAD

**Issue by kevinpuj** [Tweechable/tweechable_final#29]
Need a way, whether contact form on website or a twitter command, a user needs to be able to indicate their twitter ID (for example, @KimKardashian, not "Kim Kardashian West" , or maybe based on some other, more permanent user ID, I dunno, if you're reading this, you know the twitter API better than I do)

**Comment by vkoves** [comment]
Discussion with @McEileen and @javierforero brought us to the decision that we will make it so that a user can tweet at us to unsubscribe, probably by saying *@tweechable STOP* or something of similar effect. This is to make sure that users don't unsubscribe other users. To implement this, we will build a database table of blacklisted users which will be checked before any new tweets are sent out.

**Comment by vkoves** [comment]
Did some research with @alexstevenson19, and we can put this into `self.generate_mention(tweet)` in the `Mention` model. To implement this we would check if the tweet matches a given text, and then retrieve the handle of the author of the tweet using the `:user` attribute of the tweet. We probably want to store the user's id and their handle so that we can hopefully check the user id to verify a user is not on our unsubscribe list, but if not, use the handle.

**Comment by vkoves** [comment]
I've started working on this (and created a model for unsubscribed users), and have put it up in a branch called `tweechable_unsubscribe`
