### ISSUE TITLE
Ruby version 2.4.0 not compatible

### ISSUE THREAD

**Issue by romanjesus** [Tweechable/tweechable_final#87]
Stacklevel too deep error with latest version of ruby (2.4.0)

Should specify which ruby version to use with this project on the ReadMe

<img width="1274" alt="screen shot 2017-01-24 at 8 40 53 pm" src="https://cloud.githubusercontent.com/assets/19498034/22275894/701d9ef2-e275-11e6-88e4-cad79ff947e0.png">

**Comment by McEileen** [comment]
Hi, I'm going to (belatedly...) close this issue because our getting started guide says the Ruby version is 2.3.1 and I just now edited the readme to specify the ruby version.  Let us know if there are any follow-up changes you think we should make, like providing more instructions about how to install a specific Ruby version or set the Ruby version for a directory.  (Or submit a PR with a change and someone will review it.) Thanks for the input!
